//! # Validation Engine (Server-Side Verifier Engine)
//! 
//! Wraps the core ZKP mathematics to safely deserialize the robust 64-byte payload 
//! generated by the Prover, mapping it back onto the Ristretto255 curve securely to verify.

use curve25519_dalek::ristretto::CompressedRistretto;
use merlin::Transcript;
use zkprust_core::error::ZKPError;
use zkprust_core::sigma::{Proof, VerifyingKey};

pub struct ValidationEngine;

impl ValidationEngine {
    /// Consumes a raw 64-byte payload from the network, securely decompresses it
    /// into a mathematical Proof, and verifies it against the user's `VerifyingKey` (Public Key).
    ///
    /// Returns `Ok(())` if the proof mathematically proves knowledge of the secret.
    pub fn verify_payload(payload: &[u8; 64], public_key_bytes: &[u8; 32]) -> Result<(), ZKPError> {
        let proof = Proof::from_bytes(payload)?;

        let pk_compressed = CompressedRistretto::from_slice(public_key_bytes)
            .map_err(|_| ZKPError::VerificationFailed)?;
            
        let pk_point = pk_compressed.decompress()
            .ok_or(ZKPError::VerificationFailed)?;

        // Safety: We reconstruct the VerifyingKey cleanly because we cannot expose private fields inherently.
        // We will need to access the module to allow raw instantiation, or we add an API inside `zkprust_core::sigma::VerifyingKey`
        // Since `point` is pub(crate), we can just expose a `from_point` method in `zkprust_core` or do it here if possible. Wait, `VerifyingKey` `point` is `pub(crate)`! We can't access it from `zkprust-verifier`! 
        // We must update `zkprust-core` to expose `VerifyingKey::from_point(point: RistrettoPoint)`.
        let verifying_key = VerifyingKey::from_point(pk_point);
        
        // Use a strictly deterministic transcript matching the Prover's.
        let mut transcript = Transcript::new(b"gabanode_auth_protocol");

        // Verify the mathematical soundness of the proof against the transcript.
        proof.verify(&mut transcript, &verifying_key)
    }
}
